'use client';

import React from 'react';
import { InvestmentReport } from '@/types';
import { CompanyOverview } from './CompanyOverview';
import { ExecutiveSummary } from './ExecutiveSummary';
import { BusinessModel } from './BusinessModel';
import { FinancialSnapshot } from './FinancialSnapshot';
import { LatestNews } from './LatestNews';
import { SwotAnalysis } from './SwotAnalysis';
import { CompetitiveAnalysis } from './CompetitiveAnalysis';
import { RiskAssessment } from './RiskAssessment';
import { InvestmentScore } from './InvestmentScore';
import { FinalDecision } from './FinalDecision';
import { SourcesList } from './SourcesList';
import { Button } from './ui/button';
import { useToast } from './ui/toast';
import { ArrowLeft, Copy, Printer, Check, Share2, AlertTriangle } from 'lucide-react';

interface ResearchDashboardProps {
  report: InvestmentReport;
  onBack: () => void;
}

export function ResearchDashboard({ report, onBack }: ResearchDashboardProps) {
  const { success, error } = useToast();
  const [copied, setCopied] = React.useState(false);

  const handleCopy = async () => {
    try {
      const markdownSummary = `
# InvestIQ AI - Investment Research Report: ${report.company.name} (${report.company.ticker})
## Recommendation: ${report.decision} (Confidence: ${report.confidence}%)
### Investment Horizon: ${report.horizon}

## Executive Summary
${report.summary}

## Financial Snapshot
- Revenue: ${report.financials.revenue}
- Net Income: ${report.financials.net_income}
- Operating Margin: ${report.financials.operating_margin}
- P/E Ratio: ${report.financials.pe_ratio}
- EPS: ${report.financials.eps}

## SWOT Analysis
- Strengths: ${report.strengths.join(', ')}
- Weaknesses: ${report.weaknesses.join(', ')}
- Opportunities: ${report.opportunities.join(', ')}
- Threats: ${report.threats.join(', ')}

## Investment Thesis & Decision
${report.reason}

*Generated by InvestIQ AI on ${new Date().toLocaleDateString()}*
`;
      await navigator.clipboard.writeText(markdownSummary.trim());
      setCopied(true);
      success('Copied to clipboard', 'Report summary has been copied as Markdown.');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error(err);
      error('Failed to copy', 'Could not copy report details.');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-8 animate-fadeIn max-w-6xl mx-auto px-4 pb-16">
      {/* Header controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-neutral-800/40 pb-6 no-print">
        {/* Back Button */}
        <Button variant="ghost" size="sm" onClick={onBack} className="self-start">
          <ArrowLeft className="h-4 w-4 mr-2" />
          <span>Research another company</span>
        </Button>

        {/* Action Controls */}
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? (
              <Check className="h-4 w-4 mr-2 text-emerald-400" />
            ) : (
              <Copy className="h-4 w-4 mr-2" />
            )}
            <span>{copied ? 'Copied' : 'Copy Report'}</span>
          </Button>

          <Button variant="default" size="sm" onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2" />
            <span>Export as PDF</span>
          </Button>
        </div>
      </div>

      {/* Demo Mode Banner */}
      {report.isDemo && (
        <div className="no-print flex items-start gap-3 p-4 bg-amber-500/5 border border-amber-500/20 rounded-2xl text-amber-300 text-xs leading-normal">
          <AlertTriangle className="h-5 w-5 shrink-0 text-amber-400 mt-0.5" />
          <div>
            <span className="font-bold block mb-0.5">Demo Mode Active</span>
            <span>
              Live web search was bypassed because no <code className="text-amber-250 font-mono">TAVILY_API_KEY</code> was configured in your `.env.local`. The company statistics and news shown below are simulated baseline metrics, but the **Gemini 2.5 Flash LLM reasoning, SWOT compilation, and final score evaluation** are fully live!
            </span>
          </div>
        </div>
      )}

      {/* Grid Dashboard */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Row 1: Company Profile (2/3 width) and Gauge Score (1/3 width) */}
        <div className="lg:col-span-2">
          <CompanyOverview company={report.company} />
        </div>
        <div className="lg:col-span-1">
          <InvestmentScore score={report.score} />
        </div>

        {/* Row 2: Final Verdict (Full Width) */}
        <div className="lg:col-span-3">
          <FinalDecision report={report} />
        </div>

        {/* Row 3: Summary (2/3 width) and SWOT Analysis (1/3 width) */}
        <div className="lg:col-span-2">
          <ExecutiveSummary summary={report.summary} />
        </div>
        <div className="lg:col-span-1">
          <SwotAnalysis
            strengths={report.strengths}
            weaknesses={report.weaknesses}
            opportunities={report.opportunities}
            threats={report.threats}
          />
        </div>

        {/* Row 4: Business Model (2/3 width) and Competitors (1/3 width) */}
        <div className="lg:col-span-2">
          <BusinessModel model={report.business_model} />
        </div>
        <div className="lg:col-span-1">
          <CompetitiveAnalysis competitors={report.competitors} />
        </div>

        {/* Row 5: Financial Metrics & Trends (Full width) */}
        <div className="lg:col-span-3">
          <FinancialSnapshot financials={report.financials} />
        </div>

        {/* Row 6: Risk Assessment (Full width) */}
        <div className="lg:col-span-3">
          <RiskAssessment risks={report.risks} />
        </div>

        {/* Row 7: Latest News & Sentiment (Full width) */}
        <div className="lg:col-span-3">
          <LatestNews news={report.latest_news} />
        </div>

        {/* Row 8: References (Full width) */}
        <div className="lg:col-span-3">
          <SourcesList sources={report.sources} />
        </div>
      </div>
    </div>
  );
}
